#!/bin/bash

$SNAP/opt/Autodesk/AdskLicensing/12.1.0.7121/helper/AdskLicensingInstHelper register -pk 657O1 -pv 2023.0.0.F -el EN_US -cf $SNAP/var/opt/Autodesk/Adlm/Maya2023/MayaConfig.pit

mkdir -p $HOME/maya/2023
echo "MAYA_DISABLE_ADP=1" >> $HOME/maya/2023/Maya.env
echo "LC_ALL=C" >> $HOME/maya/2023/Maya.env
